version: "3.8"

services:
  psql:
    container_name: psql
    image: postgres:13.1
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: joren
      POSTGRES_PASSWORD: grapefruits

# persist these volumes
volumes:
  psql-data:
